import type { CareData, ExtractionDraft } from './types';
import { addDays, getTodayLocalDate } from './date';
import { defaultUserSettings } from './water';

const today = getTodayLocalDate();
const demoCourseId = 'demo-course-current';

export const demoData: CareData = {
  treatmentCourses: [
    {
      id: demoCourseId,
      name: 'Đợt da liễu tháng này',
      startedAt: today,
      status: 'active',
      source: 'demo',
      createdAt: new Date().toISOString(),
    },
  ],
  activeCourseId: demoCourseId,
  medications: [
    {
      id: 'demo-isotretinoin',
      courseId: demoCourseId,
      patientName: 'Trang',
      name: 'Dokreal 25mg',
      genericName: 'Isotretinoin',
      strength: '25mg',
      instructions: 'Uống ngày 1 viên sau ăn tối.',
      form: 'viên',
      source: 'demo',
      startDate: today,
      endDate: addDays(today, 29),
      scheduleTimes: ['20:30'],
      durationDays: 30,
      quantity: 30,
      remaining: 30,
      doctorNotes: 'Không mang thai, không cho con bú trong khi dùng thuốc và 1 tháng sau khi dừng.',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'demo-heparos',
      courseId: demoCourseId,
      patientName: 'Trang',
      name: 'Heparos 250mg + 250mg',
      genericName: 'L-Cystine + choline bitartrate',
      instructions: 'Uống ngày 2 viên: sáng 1 viên, tối 1 viên sau ăn.',
      form: 'viên',
      source: 'demo',
      startDate: today,
      endDate: addDays(today, 29),
      scheduleTimes: ['08:30', '20:30'],
      durationDays: 30,
      quantity: 60,
      remaining: 60,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'demo-monithin',
      courseId: demoCourseId,
      patientName: 'Trang',
      name: 'Monithin 30ml',
      genericName: 'Clindamycin',
      instructions: 'Bôi mụn sáng, chiều. Bôi 30 ngày.',
      form: 'lọ',
      source: 'demo',
      startDate: today,
      endDate: addDays(today, 29),
      scheduleTimes: ['07:45', '17:45'],
      durationDays: 30,
      quantity: 1,
      remaining: 1,
      createdAt: new Date().toISOString(),
    },
  ],
  doseEvents: [],
  appointments: [
    {
      id: 'demo-appointment',
      courseId: demoCourseId,
      title: 'Tái khám da liễu',
      clinic: 'Bệnh viện Da liễu TW',
      appointmentAt: `${addDays(today, 30)}T09:00:00+07:00`,
      notes: 'Mang theo đơn này khi tái khám.',
      createdAt: new Date().toISOString(),
    },
  ],
  doctorNotes: [
    {
      id: 'demo-note-1',
      courseId: demoCourseId,
      note: 'Tránh nắng. Không uống vitamin A, thuốc nhóm cycline.',
      category: 'warning',
      pinned: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: 'demo-note-2',
      courseId: demoCourseId,
      note: 'Hạn chế thức khuya, rượu bia, sữa bò và đồ cay nóng.',
      category: 'care',
      pinned: true,
      createdAt: new Date().toISOString(),
    },
  ],
  userSettings: {
    ...defaultUserSettings,
    onboardingCompleted: true,
    displayName: 'Trang',
  },
  healthPhotoEntries: [],
};

export const demoExtractionDraft: ExtractionDraft = {
  patientName: 'Trang',
  medicines: [
    {
      name: 'Isotretinoin 25mg (Dokreal 25mg)',
      rawNameLine: 'Isotretinoin 25mg (Dokreal 25mg)',
      genericName: 'Isotretinoin',
      brandName: 'Dokreal',
      strength: '25mg',
      form: 'viên',
      instructions: 'Uống ngày 1 viên sau ăn tối.',
      scheduleTimes: ['20:30'],
      durationDays: 30,
      quantity: 30,
      confidence: 0.86,
      needsReview: ['Xác nhận giờ uống buổi tối'],
    },
    {
      name: 'Heparos 250mg + 250mg',
      form: 'viên',
      instructions: 'Uống ngày 2 viên, sáng 1 viên, tối 1 viên sau ăn.',
      scheduleTimes: ['08:30', '20:30'],
      durationDays: 30,
      quantity: 60,
      confidence: 0.83,
    },
    {
      name: 'Cefixime (Cefimed 200mg)',
      rawNameLine: 'Cefixime (Cefimed 200mg)',
      genericName: 'Cefixime',
      brandName: 'Cefimed',
      strength: '200mg',
      form: 'viên',
      instructions: 'Uống ngày 2 viên, sáng 1 viên, tối 1 viên. Uống 10 ngày.',
      scheduleTimes: ['08:30', '20:30'],
      durationDays: 10,
      quantity: 20,
      confidence: 0.8,
      needsReview: ['Xác nhận đây là kháng sinh và thời điểm uống theo đơn gốc'],
    },
    {
      name: 'Clindamycin (dưới dạng clindamycin phosphat 11.88mg) 10mg/1ml (Monithin 30ml)',
      rawNameLine: 'Clindamycin (dưới dạng clindamycin phosphat 11.88mg) 10mg/1ml (Monithin 30ml)',
      genericName: 'Clindamycin',
      brandName: 'Monithin',
      form: 'lọ',
      instructions: 'Bôi mụn sáng, chiều. Bôi 30 ngày.',
      scheduleTimes: ['07:45', '17:45'],
      durationDays: 30,
      quantity: 1,
      confidence: 0.82,
    },
    {
      name: 'Adalcrem plus 15g (Adapalene 15mg + Clindamycin 150mg)',
      rawNameLine: 'Adalcrem plus 15g (Adapalene 15mg + Clindamycin 150mg)',
      genericName: 'Adapalene + Clindamycin',
      brandName: 'Adalcrem plus',
      form: 'tuýp',
      instructions: 'Bôi mụn buổi tối.',
      scheduleTimes: ['21:30'],
      durationDays: 30,
      quantity: 1,
      confidence: 0.78,
      needsReview: ['Xác nhận giờ bôi buổi tối'],
    },
  ],
  doctorNotes: [
    'Tránh nắng.',
    'Không có thai và cho con bú trong khi dùng thuốc.',
    'Tái khám sau 1 tháng.',
  ],
  appointments: [
    {
      title: 'Tái khám sau 1 tháng',
      notes: 'Mang theo đơn này.',
    },
  ],
  warnings: ['Kết quả AI chỉ là bản nháp; cần đối chiếu với đơn gốc trước khi lưu.'],
};
